In [1]:
import numpy as np 

In [5]:
# 2. Create arrays
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
# 3. Operations using broadcasting
print("Addition:\n", arr1 + arr2)
print("---------------------------------------")
print("Subtraction:\n", arr1 - arr2)
print("---------------------------------------")
print("Multiplication:\n", arr1 * arr2)
print("---------------------------------------")
print("Division:\n", arr1 / arr2)

print("---------------------------------------")
# 4. Broadcasting Explanation
# Broadcasting allows NumPy to perform operations on arrays of different shapes.
# Here, arr2 (1D) is automatically expanded to match arr1 (2D) shape.

# 5. Universal Functions
arr3 = np.array([1,4,9,16,25])

print("\nSquare Root:", np.sqrt(arr3))
print("Exponential:", np.exp(arr3))
print("Sine:", np.sin(arr3))
print("---------------------------------------")

# 6. Array operations
arr4 = np.array([[5,12,3],[8,2,7]])

print("\nSum of all elements:", np.sum(arr4))
print("Max in each column:", np.max(arr4, axis=0))
print("Min in each row:", np.min(arr4, axis=1))
print("---------------------------------------")

# 7. Type casting
arr1_float = arr1.astype(float)
print("\narr1 as float:\n", arr1_float)
print("---------------------------------------")

Addition:
 [[11 22 33]
 [14 25 36]]
---------------------------------------
Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]
---------------------------------------
Multiplication:
 [[ 10  40  90]
 [ 40 100 180]]
---------------------------------------
Division:
 [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]
---------------------------------------

Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
---------------------------------------

Sum of all elements: 37
Max in each column: [ 8 12  7]
Min in each row: [3 2]
---------------------------------------

arr1 as float:
 [[1. 2. 3.]
 [4. 5. 6.]]
---------------------------------------
