In [5]:
import numpy as np 

In [6]:
# 2. Create Arrays
A = np.array([2,4,6,8,10,12,14,16,18,20])

# Array B 
B = np.zeros((3,3))

# Array C 
C = np.random.randint(1, 101, 5)

# Array D 
D = np.linspace(0, 5, 10)
print("------------------------------------")
print("Array A:", A)
print("------------------------------------")
print("Array B:\n", B)
print("------------------------------------")
print("Array C:", C)
print("------------------------------------")
print("Array D:", D)
print("------------------------------------")

# 3. Properties of Array A
print("\n--- Array A Properties ---")
print("Shape:", A.shape)
print("Data Type:", A.dtype)
print("Size:", A.size)
print("Dimensions:", A.ndim)
print("------------------------------------")

# 4. Operations on Array A
print("\n--- Operations on Array A ---")

# Reshape to 2x5
A_reshaped = A.reshape(2,5)
print("Reshaped A (2x5):\n", A_reshaped)

print("------------------------------------")
# Max value and index
print("Max Value:", A.max())
print("Index of Max Value:", A.argmax())
print("------------------------------------")

# Min value and index
print("Min Value:", A.min())
print("Index of Min Value:", A.argmin())
print("------------------------------------")

# 5. Array E
E = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Element at row 1, column 2
print("\nElement at row 1, column 2:", E[1,2])

------------------------------------
Array A: [ 2  4  6  8 10 12 14 16 18 20]
------------------------------------
Array B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------
Array C: [ 1 43 63 20 97]
------------------------------------
Array D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
------------------------------------

--- Array A Properties ---
Shape: (10,)
Data Type: int64
Size: 10
Dimensions: 1
------------------------------------

--- Operations on Array A ---
Reshaped A (2x5):
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
------------------------------------
Max Value: 20
Index of Max Value: 9
------------------------------------
Min Value: 2
Index of Min Value: 0
------------------------------------

Element at row 1, column 2: 6
